name: "Detect snapshot"

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

jobs:
    detectSnapshot:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
            -   name: Detect SNAPSHOT
                run: scripts/analysis/detectSNAPSHOT.sh
