name: Unit tests

on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master, stable-* ]

permissions:
    contents: read
    pull-requests: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
            -   name: Set up JDK 11
                uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
                with:
                    distribution: "temurin"
                    java-version: 11
            -   name: Delete old comments
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                if: ${{ always() }}
                run: scripts/deleteOldComments.sh "test" "Unit" ${{github.event.number}}
            -   name: Run unit tests with coverage
                uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629 # v2.4.2
                with:
                    arguments: jacocoTestGplayDebugUnitTest
            -   name: Upload failing results
                if: ${{ failure() }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: scripts/uploadReport.sh "${{ secrets.LOG_USERNAME }}" "${{ secrets.LOG_PASSWORD }}" ${{github.event.number}} "test" "Unit" ${{github.event.number}}
            -   name: Upload coverage to codecov
                uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2 # v3.1.3
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    flags: unit
                    fail_ci_if_error: true
            -   name: Upload jacoco artifacts
                if: ${{ failure() }}
                uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
                with:
                    name: test-results
                    path: app/build/reports/tests/testGplayDebugUnitTest/
